# Sudo is required for docker
sudo: required

# Enable docker
services:
  - docker

go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci